# Generated by Django 6.0.3 on 2026-03-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecritique', '0004_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
