# Generated by Django 6.0.3 on 2026-03-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecritique', '0005_game_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='game',
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gamecritique.review'),
        ),
    ]
