# Generated by Django 6.0.3 on 2026-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecritique', '0005_game_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_key',
            field=models.BooleanField(default=False),
        ),
    ]
