# Generated by Django 6.0.3 on 2026-03-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamecritique', '0006_remove_comment_game_comment_review'),
        ('gamecritique', '0007_alter_userprofile_user'),
    ]

    operations = [
    ]
