# Generated by Django 6.0.3 on 2026-03-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecritique', '0008_merge_20260323_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_donuts',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
